name: CI
on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  automerge:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          target: minor
